version: "3.5"

services:
  admin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - db:mysql
    depends_on:
      - db
    ports:
      - "8183:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Chat

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./backend/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --daemonize yes
